[package]
name              = "pack-api"
version           = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow              = { workspace = true, features = ["backtrace"] }
bincode             = { workspace = true }
futures             = { workspace = true }
## turbpack specific
pack-core           = { workspace = true }
parking_lot         = { workspace = true }
qstring             = { workspace = true }
rustc-hash          = { workspace = true }
serde               = { workspace = true }
serde_json          = { workspace = true }
simd-json           = { workspace = true, features = ["arraybackend"] }
tokio               = { workspace = true, features = ["sync"] }
tracing             = { workspace = true }
turbo-bincode       = { workspace = true }
turbo-rcstr         = { workspace = true }
turbo-tasks         = { workspace = true }
turbo-tasks-backend = { workspace = true }
turbo-tasks-env     = { workspace = true }
turbo-tasks-fs      = { workspace = true }
turbo-unix-path     = { workspace = true }
turbopack           = { workspace = true }
turbopack-browser   = { workspace = true }
turbopack-core      = { workspace = true }
turbopack-css       = { workspace = true }
turbopack-node      = { workspace = true, default-features = false }
turbopack-nodejs    = { workspace = true }
turbopack-resolve   = { workspace = true }
turbopack-static    = { workspace = true }
url                 = { workspace = true }
urlencoding         = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
vergen = { version = "9.0.6", features = ["cargo"] }

[lints]
workspace = true
