# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[default.extend-identifiers]
# POSIX open(2) flags
WRONLY = "WRONLY"
RDONLY = "RDONLY"

[files]
ignore-vcs = true 
extend-exclude = [
    "next.js/",
    "crates/pack-tests/tests/snapshot/**/output/",
    "crates/pack-core/js/src/node-polyfills",
    "crates/pack-core/js/src/loader-runner",
    "e2e/pm/**",
    "packages/utoo-web/src/webpackLoaders/nodePolyFillRaw",
    "packages/utoo-web/src/webpackLoaders/workerContent.js",
    "packages/utoo-web/src/utoo/index.d.ts"
]

[type.sourcemap]
extend-glob = ["*.js.map"]
check-file = false

[type.snapshot]
extend-glob = ["*.snapshot"]
check-file = false
