# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[default]

[files]
ignore-vcs = true 
extend-exclude = [
    "next.js/",
    "crates/pack-tests/tests/snapshot/**/output/",
    "crates/pack-core/js/src/node-polyfills",
    "e2e/pm/**",
    "packages/utoo-web/src/webpackLoaders/nodePolyFillRaw",
    "packages/utoo-web/src/webpackLoaders/workerContent.js"
]

[type.sourcemap]
extend-glob = ["*.js.map"]
check-file = false

[type.snapshot]
extend-glob = ["*.snapshot"]
check-file = false
