# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[default]

[files]
ignore-vcs = true 
extend-exclude = [
    "next.js/",
    "crates/pack-tests/tests/snapshot/**/output/",
    "crates/pack-core/js/src/node-polyfills",
    "packages/utooweb-loaders/src/loader-runner"
]

[type.sourcemap]
extend-glob = ["*.js.map"]
check-file = false

[type.snapshot]
extend-glob = ["*.snapshot"]
check-file = false