[package]
name = "utoo-wasm"
version = "0.1.0"
edition = "2021"

description = "WASM bindings for utoo-pm & utoo-pack"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ['serde-serialize'] }
wasm-bindgen-futures = "0.4"
reqwest = { version = "0.12.22" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
js-sys = "0.3"
petgraph = "0.6"
flate2 = "1.1.2"
tar = "0.4.44"
futures-util = "0.3.31"
futures = { workspace = true }
anyhow = { workspace = true, features = ["backtrace"] }
tracing = { workspace = true }
opfs-project = { workspace = true }

## turbpack specific
turbo-rcstr = { workspace = true }
turbo-tasks = { workspace = true }
turbo-tasks-malloc = { workspace = true }
turbo-tasks-backend = { workspace = true }
pack-core = { workspace = true }
pack-api = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
turbo-tasks-build = { workspace = true }
