[package]
name              = "pack-napi"
version           = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

# tombi: format.rules.table-keys-order.disabled = true
[dependencies]
anyhow                       = { workspace = true, features = ["backtrace"] }
bincode                      = { workspace = true }
console-subscriber           = { workspace = true, optional = true }
dhat                         = { version = "0.3.2", optional = true }
either                       = { workspace = true }
futures-util                 = { workspace = true }
napi                         = { workspace = true }
napi-derive                  = { workspace = true }
owo-colors                   = { workspace = true }
pack-api                     = { workspace = true, features = ["worker_pool_napi"] }
pack-core                    = { workspace = true }
rand                         = { workspace = true }
rustc-hash                   = { workspace = true }
serde                        = { workspace = true }
serde_json                   = { workspace = true }
swc_core                     = { workspace = true, features = [
  "base",
  "common_concurrent",
  "ecma_ast",
  "ecma_ast_serde",
  "ecma_codegen",
  "ecma_helpers_inline",
  "ecma_loader_lru",
  "ecma_loader_node",
  "ecma_minifier",
  "ecma_parser",
  "ecma_parser_typescript",
  "ecma_transforms",
  "ecma_transforms_optimization",
  "ecma_transforms_react",
  "ecma_transforms_typescript",
  "ecma_utils",
  "ecma_visit",
] }
tracing                      = { workspace = true }
tracing-chrome               = "0.7.2"
tracing-subscriber           = { workspace = true, features = ["chrono"] }
turbopack-ecmascript-plugins = { workspace = true, optional = true }
urlencoding                  = { workspace = true }

[build-dependencies]
anyhow       = { workspace = true }
napi-build   = "2"
serde        = { workspace = true }
serde_json   = { workspace = true }
vergen-gitcl = { version = "1.0.8", features = ["cargo"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
hyper                             = { version = "0.14", features = ["full"] }
mime_guess                        = "2.0.4"
pack-api                          = { workspace = true, features = ["process_pool"] }
pack-core                         = { workspace = true, features = ["process_pool"] }
tokio                             = { workspace = true, features = ["full"] }
turbo-rcstr                       = { workspace = true, features = ["napi"] }
turbo-tasks                       = { workspace = true }
turbo-tasks-backend               = { workspace = true }
turbo-tasks-fs                    = { workspace = true }
turbo-tasks-malloc                = { workspace = true, default-features = false, features = ["custom_allocator"] }
turbo-unix-path                   = { workspace = true }
turbopack                         = { workspace = true }
turbopack-core                    = { workspace = true }
turbopack-dev-server              = { workspace = true }
turbopack-ecmascript-hmr-protocol = { workspace = true }
turbopack-ecmascript-plugins      = { workspace = true, optional = true }
turbopack-node                    = { workspace = true, default-features = false, features = ["worker_pool_napi"] }
turbopack-trace-server            = { workspace = true }
turbopack-trace-utils             = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = "0.60"

[features]
# Enable dhat profiling allocator for ad hoc profiling.
# [Note]: we do not have any ad hoc event in the codebase yet, so enabling this
# effectively does nothing.
__internal_dhat-ad-hoc = ["dhat"]
# Enable dhat profiling allocator for heap profiling.
__internal_dhat-heap   = ["dhat"]
plugin                 = [
  "pack-core/plugin",
  "swc_core/plugin_transform_host_native",
  "swc_core/plugin_transform_host_native_filesystem_cache",
  "swc_core/plugin_transform_host_native_shared_runtime",
]
# Enable support for the tokio console: https://github.com/tokio-rs/console
tokio-console          = ["dep:console-subscriber"]

[lints]
workspace = true
