#!/bin/bash
# Phase-isolated cold-install bench: resolve vs cold-install vs warm-link.
# utoo vs bun only (they're the PMs with a true --lockfile-only mode).
set -eo pipefail

# --- config ---
PROJECT=${PROJECT:-ant-design}
REGISTRY=${REGISTRY:-https://registry.npmjs.org}
RUNS=${BENCH_RUNS:-3}
IFS=',' read -ra PACKAGE_MANAGERS <<< "${PM_LIST:-utoo,bun}"

BENCH_DIR=${BENCH_DIR:-/tmp/pm-bench}
RESULTS_DIR=${RESULTS_DIR:-/tmp/pm-bench-results}
mkdir -p "$BENCH_DIR" "$RESULTS_DIR"

UTOO_CACHE="$HOME/.cache/nm"
BUN_CACHE="$HOME/.bun/install/cache"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

banner() { echo -e "${YELLOW}=== $* ===${NC}"; }

# --- project ---
banner "Preparing $PROJECT"
cd "$BENCH_DIR"
if [ ! -d "$PROJECT" ]; then
  git clone --depth=1 "https://github.com/ant-design/${PROJECT}.git" "$PROJECT"
fi
PROJECT_DIR="$BENCH_DIR/$PROJECT"

# --- inline prepare snippets (passed to hyperfine --prepare via bash -c) ---
# Each snippet is self-contained so it works in the subshell hyperfine spawns.
snip_reset_nm="cd $PROJECT_DIR && rm -rf node_modules && find . -maxdepth 4 -type d -path '*/packages/*/node_modules' -exec rm -rf {} + 2>/dev/null || true"
snip_reset_all="cd $PROJECT_DIR && git clean -dfx > /dev/null && rm -rf '$UTOO_CACHE' '$BUN_CACHE'"

prepare_cmd() {
  local phase=$1 pm=$2
  case "$phase:$pm" in
    p1:*)      echo "$snip_reset_all" ;;
    p3:utoo)   echo "$snip_reset_nm && rm -rf '$UTOO_CACHE'" ;;
    p3:bun)    echo "$snip_reset_nm && rm -rf '$BUN_CACHE'" ;;
    p4:utoo|p4:bun)
      # Warm-link: keep cache, drop node_modules. Lockfile + cache are
      # guaranteed to exist by the one-off warmup before phase 4 starts.
      echo "$snip_reset_nm" ;;
  esac
}

install_cmd() {
  case "$1" in
    utoo) echo "utoo install --ignore-scripts --registry=$REGISTRY" ;;
    bun)  echo "bun install --ignore-scripts --registry=$REGISTRY" ;;
  esac
}

resolve_cmd() {
  case "$1" in
    utoo) echo "utoo deps --registry=$REGISTRY" ;;
    bun)  echo "bun install --lockfile-only --registry=$REGISTRY" ;;
  esac
}

warmup_cache() {
  # Run one full install to fill cache. Idempotent: skips if cache already exists.
  local pm=$1
  local cache
  case "$pm" in utoo) cache=$UTOO_CACHE ;; bun) cache=$BUN_CACHE ;; esac
  [ -d "$cache" ] && [ -n "$(ls -A "$cache" 2>/dev/null)" ] && return
  echo -e "  ${CYAN}one-off: populating $pm cache${NC}"
  cd "$PROJECT_DIR"
  eval "$(install_cmd "$pm")" > "$RESULTS_DIR/warmup_${pm}.log" 2>&1 || {
    echo -e "  ${RED}warmup install failed for $pm (see $RESULTS_DIR/warmup_${pm}.log)${NC}"
    return 1
  }
  rm -rf node_modules
}

run_phase() {
  local phase=$1 pm=$2 cmd=$3
  local json="$RESULTS_DIR/${PROJECT}_${phase}_${pm}.json"
  local prep
  prep=$(prepare_cmd "$phase" "$pm")

  echo -e "  ${CYAN}$pm${NC} · $phase"
  if ! hyperfine \
    --runs "$RUNS" \
    --prepare "bash -c \"$prep\"" \
    --export-json "$json" \
    --show-output \
    -n "${pm}-${phase}" \
    "bash -c \"cd $PROJECT_DIR && $cmd\""; then
    echo -e "  ${RED}$pm $phase failed${NC}"
  fi
}

# === PHASE 1: resolve only (clean slate) ===
banner "Phase 1 · resolve (lockfile only, cold cache)"
for pm in "${PACKAGE_MANAGERS[@]}"; do
  run_phase "p1_resolve" "$pm" "$(resolve_cmd "$pm")"
done

# === PHASE 3: cold install (lockfile exists, cache empty) ===
banner "Phase 3 · cold install (lockfile present, empty cache, empty node_modules)"
for pm in "${PACKAGE_MANAGERS[@]}"; do
  # Lockfile was generated by phase 1, it persists in the project dir across
  # hyperfine iterations because `snip_reset_nm` only deletes node_modules.
  run_phase "p3_cold_install" "$pm" "$(install_cmd "$pm")"
done

# === PHASE 4: warm link (cache populated, lockfile exists) ===
banner "Phase 4 · warm link (lockfile present, populated cache, empty node_modules)"
for pm in "${PACKAGE_MANAGERS[@]}"; do
  warmup_cache "$pm"
  run_phase "p4_warm_link" "$pm" "$(install_cmd "$pm")"
done

# === SUMMARY ===
banner "Summary"
RESULTS_DIR="$RESULTS_DIR" node -e "
  const fs = require('fs'), path = require('path');
  const dir = process.env.RESULTS_DIR;
  const order = ['p1_resolve', 'p3_cold_install', 'p4_warm_link'];
  const byPhase = Object.fromEntries(order.map(p => [p, []]));
  for (const f of fs.readdirSync(dir).filter(x => x.endsWith('.json'))) {
    let data;
    try { data = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')); }
    catch (_) { continue; }
    for (const r of data.results) {
      const phase = order.find(p => r.command.includes(p) || f.includes(p));
      if (!phase) continue;
      byPhase[phase].push({ name: r.command, mean: r.mean, stddev: r.stddev });
    }
  }
  const pad = (s, n) => String(s).padEnd(n);
  const padR = (s, n) => String(s).padStart(n);
  for (const phase of order) {
    if (byPhase[phase].length === 0) continue;
    console.log('\n## ' + phase);
    console.log(pad('PM', 24) + ' ' + padR('mean', 9) + '   ' + padR('stddev', 7));
    for (const r of byPhase[phase]) {
      console.log(pad(r.name, 24) + ' ' + padR(r.mean.toFixed(2) + 's', 9) + '   ' + padR(r.stddev.toFixed(2) + 's', 7));
    }
  }
"

echo -e "${GREEN}Done. Raw results in $RESULTS_DIR${NC}"
