[env]
UTOO_WORKSPACE_DIR = { value = "", relative = true }

[build]
rustflags = [
  "--cfg",
  "tokio_unstable",
]

[cache]
auto-clean-frequency = "1 day"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-C",
  "target-feature=+crt-static"
]

[target.wasm32-unknown-unknown]
rustflags = [
  "--cfg",
  "tokio_unstable",
  "--cfg",
  'getrandom_backend="wasm_js"',
  "-Ctarget-feature=+atomics,+bulk-memory,+crt-static,+exception-handling,+extended-const,+multivalue,+mutable-globals,+nontrapping-fptoint,+reference-types,+relaxed-simd,+sign-ext,+simd128,+tail-call",
  "-Clink-arg=--shared-memory",
  "-Clink-arg=--import-memory",
  "-Clink-arg=--initial-memory=67108864",
  "-Clink-arg=--max-memory=4294967296",
  "-Clink-arg=--export=__wasm_init_tls",
  "-Clink-arg=--export=__tls_size",
  "-Clink-arg=--export=__tls_align",
  "-Clink-arg=--export=__tls_base",
  "-Aunused",
]

[unstable.git]
shallow_index = true
shallow_deps = true

[unstable.gitoxide]
fetch = true
checkout = true
list_files = true
internal_use_git2 = false

[alias]
format = "fmt --all --verbose"
lint = "clippy --workspace --all-targets -- --deny warnings"
