[env]
UTOO_WORKSPACE_DIR = { value = "", relative = true }

[build]
rustflags = [
  "--cfg",
  "tokio_unstable",
]

[cache]
auto-clean-frequency = "1 day"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-C",
  "target-feature=+crt-static"
]

[target.wasm32-unknown-unknown]
rustflags = [
  "-Clink-arg=--shared-memory",
  "-Clink-arg=--import-memory",
  "-Clink-arg=--initial-memory=67108864",
  "-Clink-arg=--max-memory=4294967296",
  "-Clink-arg=--export=__wasm_init_tls",
  "-Clink-arg=--export=__heap_base",
  "-Clink-arg=--export=__tls_size",
  "-Clink-arg=--export=__tls_align",
  "-Clink-arg=--export=__tls_base",
  "-Ctarget-feature=+atomics",
  "-Ctarget-feature=+bulk-memory",
  "-Ctarget-feature=+crt-static",
  "-Ctarget-feature=+exception-handling",
  "-Ctarget-feature=+extended-const",
  "-Ctarget-feature=+multivalue",
  "-Ctarget-feature=+mutable-globals",
  "-Ctarget-feature=+nontrapping-fptoint",
  "-Ctarget-feature=+reference-types",
  "-Ctarget-feature=+relaxed-simd",
  "-Ctarget-feature=+sign-ext",
  "-Ctarget-feature=+simd128",
  "-Ctarget-feature=+tail-call",
  "--cfg=tokio_unstable",
  "--cfg=getrandom_backend=\"wasm_js\"",
  "-Aunused",
]

[unstable.git]
shallow_index = true
shallow_deps = true

[unstable.gitoxide]
fetch = true
checkout = true
list_files = true
internal_use_git2 = false

[alias]
format = "fmt --all --verbose"
lint = "clippy --workspace --all-targets -- --deny warnings"
