[package]
name        = "pack-tests"
version     = "0.1.0"
edition     = "2024"
description = "TBD"
license     = "MIT"
# don't publish this crate
publish     = false
autobenches = false

[dev-dependencies]
anyhow                       = { workspace = true }
dunce                        = { workspace = true }
once_cell                    = { workspace = true }
pack-api                     = { workspace = true, features = ["process_pool"] }
pack-core                    = { workspace = true, features = ["process_pool", "test"] }
rustc-hash                   = { workspace = true }
serde                        = { workspace = true }
serde_json                   = { workspace = true }
testing                      = { workspace = true }
tokio                        = { workspace = true }
tracing-subscriber           = { workspace = true, features = ["json"] }
turbo-rcstr                  = { workspace = true }
turbo-tasks                  = { workspace = true }
turbo-tasks-backend          = { workspace = true }
turbo-tasks-bytes            = { workspace = true }
turbo-tasks-env              = { workspace = true }
turbo-tasks-fs               = { workspace = true }
turbo-unix-path              = { workspace = true }
turbopack                    = { workspace = true }
turbopack-browser            = { workspace = true, features = ["test"] }
turbopack-core               = { workspace = true }
turbopack-ecmascript-plugins = { workspace = true }
turbopack-node               = { workspace = true, default-features = false, features = ["process_pool"] }
turbopack-nodejs             = { workspace = true, features = ["test"] }
turbopack-resolve            = { workspace = true }
turbopack-test-utils         = { workspace = true }

[lints]
workspace = true
