name: utoopack-release

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'utoopack-v')
    strategy:
      fail-fast: true
      matrix:
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
            build: |
              npm run build:binding --workspace=@utoo/pack -- --target aarch64-apple-darwin
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              npm run build:binding --workspace=@utoo/pack -- --target x86_64-apple-darwin
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
            build: |
              apt-get update && apt-get install -y libc6-dev-arm64-cross libgcc-s1-arm64-cross &&
              rustup install nightly-2026-05-15 &&
              rustup default nightly-2026-05-15 &&
              rustup target add aarch64-unknown-linux-gnu &&
              npm run build:binding --workspace=@utoo/pack -- --target aarch64-unknown-linux-gnu
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
            # Note: export RUSTFLAGS for musl need inject especially: https://github.com/utooland/utoo/pull/1980
            build: |
              set -ex &&
              rm /etc/apk/repositories &&
              echo "https://dl-cdn.alpinelinux.org/alpine/v3.21/main" >> /etc/apk/repositories &&
              echo "https://dl-cdn.alpinelinux.org/alpine/v3.21/community" >> /etc/apk/repositories &&
              apk update &&
              apk add --no-cache libc6-compat pkgconfig dav1d libdav1d dav1d-dev clang-static llvm-dev &&
              rustup install nightly-2026-05-15 &&
              rustup default nightly-2026-05-15 &&
              rustup target add aarch64-unknown-linux-musl &&
              export RUSTFLAGS='--cfg tokio_unstable -Zshare-generics=y -Zthreads=8 -Zunstable-options -Csymbol-mangling-version=v0 -Clinker-flavor=gnu-lld-cc -Clink-self-contained=+linker' &&
              npm run build:binding --workspace=@utoo/pack -- --target aarch64-unknown-linux-musl
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
            build: |
              apt-get update &&
              rustup install nightly-2026-05-15 &&
              rustup default nightly-2026-05-15 &&
              rustup target add x86_64-unknown-linux-gnu &&
              npm run build:binding --workspace=@utoo/pack -- --target x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
            # Note: export RUSTFLAGS for musl need inject especially: https://github.com/utooland/utoo/pull/1980
            build: |
              set -ex &&
              rm /etc/apk/repositories &&
              echo "https://dl-cdn.alpinelinux.org/alpine/v3.21/main" >> /etc/apk/repositories &&
              echo "https://dl-cdn.alpinelinux.org/alpine/v3.21/community" >> /etc/apk/repositories &&
              apk update &&
              apk add --no-cache libc6-compat pkgconfig dav1d libdav1d dav1d-dev clang-static llvm-dev &&
              rustup install nightly-2026-05-15 &&
              rustup default nightly-2026-05-15 &&
              rustup target add x86_64-unknown-linux-musl &&
              export RUSTFLAGS='--cfg tokio_unstable -Zshare-generics=y -Zthreads=8 -Csymbol-mangling-version=v0' &&
              npm run build:binding --workspace=@utoo/pack -- --target x86_64-unknown-linux-musl
          # swc_plugin_runner not supported on aarch64 windows now
          # - host: windows-latest
          #   target: aarch64-pc-windows-msvc
          #   build: |
          #     git config --system core.longpaths true &&
          #     rustup target add aarch64-pc-windows-msvc &&
          #     npm run build:binding --workspace=@utoo/pack -- --target aarch64-pc-windows-msvc
          - host: windows-latest
            build: |
              git config --system core.longpaths true &&
              npm run build:binding --workspace=@utoo/pack -- --target x86_64-pc-windows-msvc
            target: x86_64-pc-windows-msvc
    name: utoopack-release-${{ matrix.settings.target }} - node@22
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v6
      - name: Init git submodules
        run: git submodule update --init --recursive --depth 1
      - name: Free disk space
        if: matrix.settings.host == 'ubuntu-latest'
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/share/miniconda
          sudo docker image prune --all --force
      - name: Set up QEMU
        if: matrix.settings.docker && contains(matrix.settings.target, 'aarch64')
        uses: docker/setup-qemu-action@v4
      - name: Setup node
        uses: actions/setup-node@v6
        if: ${{ !matrix.settings.docker }}
        with:
          node-version: 22.14.0
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        if: ${{ !matrix.settings.docker }}
        with:
          toolchain: nightly-2026-05-15
          targets: ${{ matrix.settings.target }}
      # - name: Cache cargo
      #   uses: Swatinem/rust-cache@v2
      #   with:
      #     shared-key: pack-release-${{ matrix.settings.target }}
      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash
      - name: Setup Utoo
        uses: utooland/setup-utoo@v1

      - name: Clear install-node for musl builds
        if: ${{ contains(matrix.settings.target, 'musl') }}
        run: |
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('package.json'));
            delete pkg.engines['install-node'];
            fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
          "

      - name: Install dependencies
        run: utoo install
      - name: Setup node x86
        uses: actions/setup-node@v6
      - name: Build in docker
        if: ${{ matrix.settings.docker }}
        run: |
          cat <<'EOF' > build_script.sh
          ${{ matrix.settings.build }}
          EOF
          chmod +x build_script.sh
          docker run --rm \
            -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db \
            -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache \
            -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index \
            -v ${{ github.workspace }}:/build \
            -w /build \
            ${{ matrix.settings.docker }} \
            /bin/sh /build/build_script.sh
      - name: Build
        run: ${{ matrix.settings.build }}
        if: ${{ !matrix.settings.docker }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pack-${{ matrix.settings.target }}
          path: ./packages/pack/src/pack.*.node
          if-no-files-found: error
  publish:
    if: github.event_name == 'release' && startsWith(github.event.release.tag_name, 'utoopack-v')
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22.14.0
          registry-url: "https://registry.npmjs.org"
      - name: Setup Utoo
        uses: utooland/setup-utoo@v1

      - name: Install dependencies
        run: utoo install
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./packages/pack/src
      - name: Move artifacts
        run: cd packages/pack && npm run artifacts
      - name: List packages
        run: cd packages/pack && ls -R ./npm
        shell: bash
      - name: Build JS
        run: |
          npm run build --workspace=@utoo/pack-shared
          npm run build:js --workspace=@utoo/pack
          npm run build --workspace=@utoo/pack-cli
      - name: Get version from release or use alpha version
        id: get_version
        shell: bash
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          VERSION=${TAG_NAME#utoopack-v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Update npm for trusted publishing
        run: npm install -g npm@11.6.2
      - name: NPM Publish
        run: |
          set -euo pipefail

          echo "${VERSION}"

          TAG="latest"
          if [[ "$VERSION" == *"-"* ]]; then
            PRERELEASE="${VERSION#*-}"
            TAG="${PRERELEASE%%.*}"
          fi
          echo "Publishing with tag: $TAG"

          npm version --workspace=@utoo/pack-shared "${VERSION}" --no-git-tag-version --workspaces-update=false &&
          npm version --workspace=@utoo/pack "${VERSION}" --no-git-tag-version --workspaces-update=false &&
          npm version --workspace=@utoo/pack-cli "${VERSION}" --no-git-tag-version --workspaces-update=false &&
          npm pkg set dependencies.@utoo/pack-shared="${VERSION}" --workspace=@utoo/pack &&
          npm pkg set dependencies.@utoo/pack="${VERSION}" --workspace=@utoo/pack-cli &&
          npm publish --workspace=@utoo/pack-shared --access public --tag "${TAG}" &&
          npm publish --workspace=@utoo/pack --access public --tag "${TAG}" &&
          npm publish --workspace=@utoo/pack-cli --access public --tag "${TAG}"
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
