name: utoopm-artifact-linux-x64

on:
  push:
    branches: ["fix/tls-native-roots"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update && apt-get install -y \
            build-essential \
            libc6-dev \
            curl \
            pkg-config \
            libssl-dev \
            git

      - uses: actions/checkout@v4

      - name: Configure git safe directory
        run: git config --global --add safe.directory /__w/utoo/utoo

      - name: Init git submodules
        run: git submodule update --init --recursive --depth 1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2026-02-18
          targets: x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build --release --bin utoo --target x86_64-unknown-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: utoo-linux-x64
          path: target/x86_64-unknown-linux-gnu/release/utoo
          retention-days: 3
