name: utoopm-ci

on:
  push:
    branches: ['next']
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
            test: |
              cargo test -p utoo-pm --target aarch64-apple-darwin
          - host: macos-latest
            target: x86_64-apple-darwin
            test: |
              rustup target add x86_64-apple-darwin &&
              cargo test -p utoo-pm --target x86_64-apple-darwin
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            test: |
              cargo test -p utoo-pm --target x86_64-unknown-linux-gnu

    name: utoopm-ci-${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Add SSH private keys for submodule repositories
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.CI_SUBMODULE }}
      - name: Init git submodules
        run: git submodule update --init
      - name: Setup node
        uses: actions/setup-node@v4
        if: ${{ !matrix.settings.docker }}
        with:
          node-version: 20
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        if: ${{ !matrix.settings.docker }}
        with:
          toolchain: nightly-2025-06-04
          targets: ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash
      - name: Install dependencies
        run: npm install
      - name: Setup node x86
        uses: actions/setup-node@v4
      - name: Test in docker
        uses: addnab/docker-run-action@v3
        if: ${{ matrix.settings.docker }}
        with:
          image: ${{ matrix.settings.docker }}
          options: "-v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index -v ${{ github.workspace }}:/build -w /build"
          run: ${{ matrix.settings.test }}
      - name: Test
        run: ${{ matrix.settings.test }}
        if: ${{ !matrix.settings.docker }}
        shell: bash
