name: utoopm-e2e

on:
  push:
    branches: ['next', 'e2e-pm']
  pull_request:
    types: [opened, synchronize]

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    name: utoopm-e2e-${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Add SSH private keys for submodule repositories
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.CI_SUBMODULE }}

      - name: Init git submodules
        run: git submodule update --init

      - name: Install x86_64 Node.js via nvm
        if: matrix.settings.target == 'x86_64-apple-darwin'
        run: |
          arch -x86_64 bash -c '
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 22
          nvm use 22
          nvm alias default 22
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
          echo "$HOME/.nvm/versions/node/v22.*/bin" >> $GITHUB_PATH
          node -p process.arch
          npm -v
          '

      - name: Setup node
        if: matrix.settings.target != 'x86_64-apple-darwin'
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-09-21
          targets: ${{ matrix.settings.target }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      # - name: Cache nm cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/nm
      #     key: e2e-nm-cache
      #     restore-keys: |
      #       e2e-nm-cache

      - name: Build utoo-pm
        run: cargo build --release --target ${{ matrix.settings.target }} --bin utoo

      - name: Update PATH with target directory
        run: echo "${{ github.workspace }}/target/${{ matrix.settings.target }}/release" >> $GITHUB_PATH

      - name: Create ut symlink for utoo
        run: ln -sf utoo $(dirname $(which utoo))/ut

      - name: Make script executable
        run: chmod +x e2e/utoo-pm.sh

      - name: Run e2e tests
        run: |
          if [ "${{ matrix.settings.target }}" = "x86_64-apple-darwin" ]; then
            arch -x86_64 bash -c '
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22
            e2e/utoo-pm.sh
            '
          else
            e2e/utoo-pm.sh
          fi
        shell: bash
