name: utoopm-release

on:
  release:
    types: [published]

# on: [ push ]

jobs:
  build-and-publish-binary:
    if: startsWith(github.event.release.tag_name, 'utoo-')
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform_os: linux
            platform_cpu: x64
            container: ubuntu:20.04
          - os: macos-latest
            target: x86_64-apple-darwin
            platform_os: darwin
            platform_cpu: x64
          - os: macos-latest
            target: aarch64-apple-darwin
            platform_os: darwin
            platform_cpu: arm64

          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
            platform_os: linux
            platform_cpu: arm64

    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Install Linux Dependencies
        if: ${{ matrix.platform_os == 'linux' }}
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update && apt-get install -y \
            build-essential \
            libc6-dev \
            libglib2.0-0 \
            curl \
            tzdata \
            pkg-config \
            libssl-dev \
            gnupg2 \
            software-properties-common \
            git
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt-get update && apt-get install -y gh

      - uses: actions/checkout@v3

      - name: Configure git safe directory
        run: |
          git config --global --add safe.directory /__w/utoo/utoo

      - name: Get version from release or use alpha version
        id: get_version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/utoo-v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/utoo-v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=0.0.0" >> $GITHUB_OUTPUT
          fi

      - name: Update Cargo.toml version
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          sed -i.bak "s/^version = \".*\"/version = \"$VERSION\"/" crates/pm/Cargo.toml
          rm crates/pm/Cargo.toml.bak

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-09-21
          override: true
          target: ${{ matrix.target }}

      - name: Add cross-compilation target for x86_64 on macOS
        if: ${{ matrix.target == 'x86_64-apple-darwin' }}
        run: rustup target add x86_64-apple-darwin

      - name: Add cross-compilation target for aarch64 on Linux
        if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Add SSH private keys for submodule repositories
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.CI_SUBMODULE }}
      - name: Init git submodules
        run: git submodule update --init

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin utoo --target ${{ matrix.target }}

      - name: Package Binaries
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ../../../utoo-${{ matrix.platform_os }}-${{ matrix.platform_cpu }}.tar.gz \
            utoo

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          ls -la
          gh release upload "${GITHUB_REF#refs/tags/}" \
            utoo-${{ matrix.platform_os }}-${{ matrix.platform_cpu }}.tar.gz --clobber

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish Binary Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          set -e
          cd vendor/scripts
          BINS=("utoo")
          for BIN in "${BINS[@]}"; do
            PACKAGE_NAME=$(echo "$BIN")
            ./npm-binary.sh "$PACKAGE_NAME" "$VERSION" \
              "../../target/${{ matrix.target }}/release/$BIN" \
              "${{ matrix.platform_os }}" "${{ matrix.platform_cpu }}"
          done

  publish-main:
    if: startsWith(github.event.release.tag_name, 'utoo-')
    needs: build-and-publish-binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Get version from release or use alpha version
        id: get_version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/utoo-v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/utoo-v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=0.0.0" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish Main utoo Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          set -e
          cd vendor/scripts
          ./npm-utoo.sh "$VERSION"
