name: taplo

on:
  push:
    branches: ["next"]
  pull_request:
    types: [opened, synchronize]

jobs:
  taplo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-10-27
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: taplo
      - name: Install Taplo
        run: cargo install taplo-cli
      - name: Taplo
        run: taplo format --check
