name: taplo
on: [pull_request]

jobs:
  taplo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-06-04
          override: true
      - name: Install Taplo
        run:
          cargo install taplo-cli
      - name: Taplo
        run:
          taplo format --check
