name: utooweb-ci

on:
  push:
    branches: ["next"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: utooweb-ci-build-wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Add SSH private keys for submodule repositories
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.CI_SUBMODULE }}
      - name: Init git submodules
        run: git submodule update --init --depth 1
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-10-27
          targets: wasm32-unknown-unknown
          components: rust-src
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: utooweb-ci
      - name: Install dependencies
        run: |
          npm install
          npm install binaryen@123.0.0 --global
          cargo install -f wasm-bindgen-cli --version 0.2.104
      - name: Build WASM
        run: |
          npm run build --workspace=@utoo/pack-shared
          npm run build:local --workspace=@utoo/web
          ls packages/utoo-web/esm/utoo
