name: utooweb-release

on:
  release:
    types: [published]

jobs:
  publish:
    if: startsWith(github.event.release.tag_name, 'utooweb-v')
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init git submodules
        run: git submodule update --init --recursive --depth 1
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2026-02-18
          targets: wasm32-unknown-unknown
          components: rust-src
      # - name: Cache cargo
      #   uses: Swatinem/rust-cache@v2
      #   with:
      #     shared-key: utooweb-release
      - name: Install dependencies
        run: |
          npm install
          npm install binaryen@123.0.0 --global
      - name: Install wasm-bindgen-cli
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: '0.2.108'
      - name: Build
        run: npx turbo run build --filter=@utoo/web
      - name: Get version from release or use alpha version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/utooweb-v}" >> $GITHUB_OUTPUT
      - name: NPM Publish
        run: |
          # npm config set provenance true
          echo "${VERSION}" &&
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc &&

          TAG="latest"
          if [[ "$VERSION" == *"-"* ]]; then
            PRERELEASE="${VERSION#*-}"
            TAG="${PRERELEASE%%.*}"
          fi
          echo "Publishing with tag: $TAG"

          npm version --workspace=@utoo/web "${VERSION}" &&
          npm publish --workspace=@utoo/web --access public --tag "${TAG}"
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
