[package]
name              = "pack-core"
version           = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
plugin = ["swc_core/plugin_transform_host_native", "turbopack-ecmascript-plugins/swc_ecma_transform_plugin"]
test   = ["turbopack-browser/test", "turbopack-ecmascript-runtime/test"]

[dependencies]
anyhow              = { workspace = true }
async-trait         = { workspace = true }
base64              = "0.22.1"
bincode             = { workspace = true }
dunce               = { workspace = true }
either              = { workspace = true, features = ["serde"] }
indoc               = { workspace = true }
mime_guess          = "2.0.4"
pathdiff            = { workspace = true }
qstring             = "0.7.2"
rustc-hash          = { workspace = true }
serde               = { workspace = true }
serde_json          = { workspace = true }
serde_path_to_error = { workspace = true }
tracing             = { workspace = true }
urlencoding         = { workspace = true }

## turbpack specific
modularize_imports = { workspace = true }
remove_console = { workspace = true }
swc_core = { workspace = true, features = [
  "base",
  "common_concurrent",
  "ecma_ast",
  "ecma_loader_lru",
  "ecma_loader_node",
  "ecma_minifier",
  "ecma_parser",
  "ecma_parser_typescript",
  "ecma_preset_env",
  "ecma_transforms",
  "ecma_transforms_optimization",
  "ecma_transforms_react",
  "ecma_transforms_typescript",
  "ecma_utils",
  "ecma_visit",
] }

turbo-bincode                = { workspace = true }
turbo-esregex                = { workspace = true }
turbo-rcstr                  = { workspace = true }
turbo-tasks                  = { workspace = true }
turbo-tasks-bytes            = { workspace = true }
turbo-tasks-env              = { workspace = true }
turbo-tasks-fs               = { workspace = true }
turbo-tasks-hash             = { workspace = true }
turbopack                    = { workspace = true }
turbopack-browser            = { workspace = true }
turbopack-core               = { workspace = true }
turbopack-css                = { workspace = true }
turbopack-ecmascript         = { workspace = true }
turbopack-ecmascript-runtime = { workspace = true }
turbopack-image              = { workspace = true }
turbopack-node               = { workspace = true, default-features = false }
turbopack-resolve            = { workspace = true }
turbopack-static             = { workspace = true }

[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dependencies]
turbo-tasks-fetch            = { workspace = true }
turbopack-ecmascript-plugins = { workspace = true, default-features = true, features = ["transform_emotion"] }

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
getrandom                    = { version = "0.3", features = ["wasm_js"] }
turbopack-ecmascript-plugins = { workspace = true, default-features = false, features = ["transform_emotion"] }

[lints]
workspace = true
